#!/usr/bin/env python3
"""Generate a unified site-data.json consumed at runtime by the static pages.

The goal: no HTML regeneration when content changes. Editing the source JSON
files (cards, taxonomy, summary) or re-ingesting docs updates the site
automatically on next reload.

Inputs (all under kg-explorer/):
- mental_models/cards.json       — 54 mental-model cards (hand-curated/mined)
- mental_models/taxonomy.json    — every entity classified into a category
- mental_models/summary.json     — counts + top models (regenerated by miner)
- lightrag_data/kv_store_doc_status.json — source-doc count

Outputs:
- kg-explorer/mental_models/site-data.json   (version-controlled copy)
- docs/mental_models/site-data.json          (served copy)

Usage: python3 build_site_data.py
"""
import json
import os
import pathlib
import re
from collections import defaultdict

ROOT = pathlib.Path(__file__).parent
MM = ROOT / "mental_models"
DOCS_MM = ROOT.parent / "docs" / "mental_models"
LIGHTRAG = ROOT / "lightrag_data"


def slugify(s: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")


def main() -> None:
    cards = json.loads((MM / "cards.json").read_text())
    taxonomy = json.loads((MM / "taxonomy.json").read_text())
    summary = json.loads((MM / "summary.json").read_text())

    # Group taxonomy entities by category, sorted alphabetically.
    categories: dict[str, list[str]] = defaultdict(list)
    for t in taxonomy:
        categories[t["category"]].append(t["entity"])
    for cat in categories:
        categories[cat].sort(key=str.lower)

    cat_counts = {cat: len(items) for cat, items in categories.items()}

    # Which cards have a generated tree page? Used by the renderer to
    # turn matching names into links instead of plain text.
    cards_dir = DOCS_MM / "cards"
    if cards_dir.exists():
        card_slugs = sorted(
            f.replace(".html", "")
            for f in os.listdir(cards_dir)
            if f.endswith(".html") and f != "index.html"
        )
    else:
        card_slugs = []

    # Doc count comes from LightRAG's doc-status store.
    doc_status_path = LIGHTRAG / "kv_store_doc_status.json"
    docs_count = 0
    if doc_status_path.exists():
        try:
            docs_count = len(json.loads(doc_status_path.read_text()))
        except Exception:
            docs_count = 0

    stats = {
        "docs": docs_count,
        "entities": summary.get("total_entities", sum(cat_counts.values())),
        "relations": summary.get("total_edges", 0),
        "cards": len(cards),
        "mental_models": cat_counts.get("MENTAL_MODEL", 0),
        "patterns": cat_counts.get("PATTERN", 0),
        "anti_patterns": cat_counts.get("ANTI_PATTERN", 0),
        "tradeoffs": cat_counts.get("TRADEOFF", 0),
        "azure_services": cat_counts.get("AZURE_SERVICE", 0),
        "processes": cat_counts.get("PROCESS", 0),
        "metrics": cat_counts.get("METRIC", 0),
        "concepts": cat_counts.get("CONCEPT", 0),
    }

    site = {
        "generated_by": "build_site_data.py",
        "stats": stats,
        "cards": cards,
        "taxonomy": dict(categories),
        "category_counts": cat_counts,
        "anti_patterns": sorted(categories.get("ANTI_PATTERN", []), key=str.lower),
        "tradeoffs": sorted(categories.get("TRADEOFF", []), key=str.lower),
        "top_mental_models": summary.get("top_mental_models", []),
        "card_slugs": card_slugs,
    }

    payload = json.dumps(site, indent=2, ensure_ascii=False)

    MM.mkdir(exist_ok=True)
    DOCS_MM.mkdir(parents=True, exist_ok=True)
    (MM / "site-data.json").write_text(payload)
    (DOCS_MM / "site-data.json").write_text(payload)

    print(f"Wrote {MM / 'site-data.json'} ({len(payload):,} bytes)")
    print(f"Wrote {DOCS_MM / 'site-data.json'} ({len(payload):,} bytes)")
    print(
        f"  stats: {stats['docs']} docs, {stats['entities']} entities, "
        f"{stats['relations']} relations, {stats['cards']} cards, "
        f"{stats['patterns']} patterns, {stats['anti_patterns']} anti-patterns"
    )


if __name__ == "__main__":
    main()
